name: "vps"

tmp_folder: "/tmp/linux-backup-script/"

sources:
    local_folders:
        - "/etc"
        - "/root"
        - "/var/www"

    mysql_databases:
        - hostname: "127.0.0.1"
          username: "root"
          password:
          charset: "utf8mb4"

containers_sequence:
    - targz:
        compression_level: "6"

    - 7zip:
        password: "test"
        volume_size: "1G"
        
    - gpg:
        password: "<enter_yours>"

storage_list:
    - aws:
        region: "<enter_yours>"
        bucket: "<enter_yours>"
        access_key_id: "<enter_yours>"
        secret_key: "<enter_yours>"
        folder: "<enter_yours>"

    - local:
        folder: "/mnt/external_storage/"

retention_periods:
    days: "3"
    weeks: "3"
    months: "3"
    years: "3"

advanced_settings:
    process_priority: "5"